package com.example.plugins.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Puja service. Represents a row in the &quot;Subastas_Puja&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.example.plugins.model.impl.PujaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.example.plugins.model.impl.PujaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Puja
 * @see com.example.plugins.model.impl.PujaImpl
 * @see com.example.plugins.model.impl.PujaModelImpl
 * @generated
 */
public interface PujaModel extends BaseModel<Puja>, StagedGroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a puja model instance should use the {@link Puja} interface instead.
     */

    /**
     * Returns the primary key of this puja.
     *
     * @return the primary key of this puja
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this puja.
     *
     * @param primaryKey the primary key of this puja
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this puja.
     *
     * @return the uuid of this puja
     */
    @AutoEscape
    @Override
    public String getUuid();

    /**
     * Sets the uuid of this puja.
     *
     * @param uuid the uuid of this puja
     */
    @Override
    public void setUuid(String uuid);

    /**
     * Returns the puja ID of this puja.
     *
     * @return the puja ID of this puja
     */
    public long getPujaId();

    /**
     * Sets the puja ID of this puja.
     *
     * @param pujaId the puja ID of this puja
     */
    public void setPujaId(long pujaId);

    /**
     * Returns the group ID of this puja.
     *
     * @return the group ID of this puja
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this puja.
     *
     * @param groupId the group ID of this puja
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this puja.
     *
     * @return the company ID of this puja
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this puja.
     *
     * @param companyId the company ID of this puja
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this puja.
     *
     * @return the user ID of this puja
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this puja.
     *
     * @param userId the user ID of this puja
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this puja.
     *
     * @return the user uuid of this puja
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this puja.
     *
     * @param userUuid the user uuid of this puja
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this puja.
     *
     * @return the user name of this puja
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this puja.
     *
     * @param userName the user name of this puja
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this puja.
     *
     * @return the create date of this puja
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this puja.
     *
     * @param createDate the create date of this puja
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this puja.
     *
     * @return the modified date of this puja
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this puja.
     *
     * @param modifiedDate the modified date of this puja
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the valor of this puja.
     *
     * @return the valor of this puja
     */
    public double getValor();

    /**
     * Sets the valor of this puja.
     *
     * @param valor the valor of this puja
     */
    public void setValor(double valor);

    /**
     * Returns the subasta ID of this puja.
     *
     * @return the subasta ID of this puja
     */
    public long getSubastaId();

    /**
     * Sets the subasta ID of this puja.
     *
     * @param subastaId the subasta ID of this puja
     */
    public void setSubastaId(long subastaId);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.example.plugins.model.Puja puja);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.example.plugins.model.Puja> toCacheModel();

    @Override
    public com.example.plugins.model.Puja toEscapedModel();

    @Override
    public com.example.plugins.model.Puja toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
