package com.example.plugins.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Subasta service. Represents a row in the &quot;Subastas_Subasta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.example.plugins.model.impl.SubastaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.example.plugins.model.impl.SubastaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Subasta
 * @see com.example.plugins.model.impl.SubastaImpl
 * @see com.example.plugins.model.impl.SubastaModelImpl
 * @generated
 */
public interface SubastaModel extends BaseModel<Subasta>, StagedGroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a subasta model instance should use the {@link Subasta} interface instead.
     */

    /**
     * Returns the primary key of this subasta.
     *
     * @return the primary key of this subasta
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this subasta.
     *
     * @param primaryKey the primary key of this subasta
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this subasta.
     *
     * @return the uuid of this subasta
     */
    @AutoEscape
    @Override
    public String getUuid();

    /**
     * Sets the uuid of this subasta.
     *
     * @param uuid the uuid of this subasta
     */
    @Override
    public void setUuid(String uuid);

    /**
     * Returns the subasta ID of this subasta.
     *
     * @return the subasta ID of this subasta
     */
    public long getSubastaId();

    /**
     * Sets the subasta ID of this subasta.
     *
     * @param subastaId the subasta ID of this subasta
     */
    public void setSubastaId(long subastaId);

    /**
     * Returns the group ID of this subasta.
     *
     * @return the group ID of this subasta
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this subasta.
     *
     * @param groupId the group ID of this subasta
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this subasta.
     *
     * @return the company ID of this subasta
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this subasta.
     *
     * @param companyId the company ID of this subasta
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this subasta.
     *
     * @return the user ID of this subasta
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this subasta.
     *
     * @param userId the user ID of this subasta
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this subasta.
     *
     * @return the user uuid of this subasta
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this subasta.
     *
     * @param userUuid the user uuid of this subasta
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this subasta.
     *
     * @return the user name of this subasta
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this subasta.
     *
     * @param userName the user name of this subasta
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this subasta.
     *
     * @return the create date of this subasta
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this subasta.
     *
     * @param createDate the create date of this subasta
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this subasta.
     *
     * @return the modified date of this subasta
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this subasta.
     *
     * @param modifiedDate the modified date of this subasta
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the precio minimo of this subasta.
     *
     * @return the precio minimo of this subasta
     */
    public double getPrecioMinimo();

    /**
     * Sets the precio minimo of this subasta.
     *
     * @param precioMinimo the precio minimo of this subasta
     */
    public void setPrecioMinimo(double precioMinimo);

    /**
     * Returns the fecha inicio of this subasta.
     *
     * @return the fecha inicio of this subasta
     */
    public Date getFechaInicio();

    /**
     * Sets the fecha inicio of this subasta.
     *
     * @param fechaInicio the fecha inicio of this subasta
     */
    public void setFechaInicio(Date fechaInicio);

    /**
     * Returns the fecha fin of this subasta.
     *
     * @return the fecha fin of this subasta
     */
    public Date getFechaFin();

    /**
     * Sets the fecha fin of this subasta.
     *
     * @param fechaFin the fecha fin of this subasta
     */
    public void setFechaFin(Date fechaFin);

    /**
     * Returns the producto ID of this subasta.
     *
     * @return the producto ID of this subasta
     */
    public long getProductoId();

    /**
     * Sets the producto ID of this subasta.
     *
     * @param productoId the producto ID of this subasta
     */
    public void setProductoId(long productoId);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.example.plugins.model.Subasta subasta);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.example.plugins.model.Subasta> toCacheModel();

    @Override
    public com.example.plugins.model.Subasta toEscapedModel();

    @Override
    public com.example.plugins.model.Subasta toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
