package com.example.plugins.model.impl;

import com.example.plugins.model.Producto;
import com.example.plugins.service.ProductoLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Producto service. Represents a row in the &quot;Subastas_Producto&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProductoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProductoImpl
 * @see com.example.plugins.model.Producto
 * @generated
 */
public abstract class ProductoBaseImpl extends ProductoModelImpl
    implements Producto {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a producto model instance should use the {@link Producto} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ProductoLocalServiceUtil.addProducto(this);
        } else {
            ProductoLocalServiceUtil.updateProducto(this);
        }
    }
}
