package com.example.plugins.model.impl;

import com.example.plugins.model.Producto;
import com.example.plugins.model.ProductoModel;
import com.example.plugins.model.ProductoSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Producto service. Represents a row in the &quot;Subastas_Producto&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.example.plugins.model.ProductoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProductoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProductoImpl
 * @see com.example.plugins.model.Producto
 * @see com.example.plugins.model.ProductoModel
 * @generated
 */
@JSON(strict = true)
public class ProductoModelImpl extends BaseModelImpl<Producto>
    implements ProductoModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a producto model instance should use the {@link com.example.plugins.model.Producto} interface instead.
     */
    public static final String TABLE_NAME = "Subastas_Producto";
    public static final Object[][] TABLE_COLUMNS = {
            { "uuid_", Types.VARCHAR },
            { "productoId", Types.BIGINT },
            { "groupId", Types.BIGINT },
            { "companyId", Types.BIGINT },
            { "userId", Types.BIGINT },
            { "userName", Types.VARCHAR },
            { "createDate", Types.TIMESTAMP },
            { "modifiedDate", Types.TIMESTAMP },
            { "nombre", Types.VARCHAR },
            { "descripcion", Types.VARCHAR },
            { "precio", Types.DOUBLE }
        };
    public static final String TABLE_SQL_CREATE = "create table Subastas_Producto (uuid_ VARCHAR(75) null,productoId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,nombre VARCHAR(75) null,descripcion VARCHAR(75) null,precio DOUBLE)";
    public static final String TABLE_SQL_DROP = "drop table Subastas_Producto";
    public static final String ORDER_BY_JPQL = " ORDER BY producto.nombre ASC";
    public static final String ORDER_BY_SQL = " ORDER BY Subastas_Producto.nombre ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.example.plugins.model.Producto"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.example.plugins.model.Producto"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.com.example.plugins.model.Producto"),
            true);
    public static long COMPANYID_COLUMN_BITMASK = 1L;
    public static long GROUPID_COLUMN_BITMASK = 2L;
    public static long NOMBRE_COLUMN_BITMASK = 4L;
    public static long PRECIO_COLUMN_BITMASK = 8L;
    public static long UUID_COLUMN_BITMASK = 16L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.example.plugins.model.Producto"));
    private static ClassLoader _classLoader = Producto.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            Producto.class
        };
    private String _uuid;
    private String _originalUuid;
    private long _productoId;
    private long _groupId;
    private long _originalGroupId;
    private boolean _setOriginalGroupId;
    private long _companyId;
    private long _originalCompanyId;
    private boolean _setOriginalCompanyId;
    private long _userId;
    private String _userUuid;
    private String _userName;
    private Date _createDate;
    private Date _modifiedDate;
    private String _nombre;
    private String _originalNombre;
    private String _descripcion;
    private double _precio;
    private double _originalPrecio;
    private boolean _setOriginalPrecio;
    private long _columnBitmask;
    private Producto _escapedModel;

    public ProductoModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static Producto toModel(ProductoSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        Producto model = new ProductoImpl();

        model.setUuid(soapModel.getUuid());
        model.setProductoId(soapModel.getProductoId());
        model.setGroupId(soapModel.getGroupId());
        model.setCompanyId(soapModel.getCompanyId());
        model.setUserId(soapModel.getUserId());
        model.setUserName(soapModel.getUserName());
        model.setCreateDate(soapModel.getCreateDate());
        model.setModifiedDate(soapModel.getModifiedDate());
        model.setNombre(soapModel.getNombre());
        model.setDescripcion(soapModel.getDescripcion());
        model.setPrecio(soapModel.getPrecio());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<Producto> toModels(ProductoSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<Producto> models = new ArrayList<Producto>(soapModels.length);

        for (ProductoSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _productoId;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setProductoId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _productoId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Producto.class;
    }

    @Override
    public String getModelClassName() {
        return Producto.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("uuid", getUuid());
        attributes.put("productoId", getProductoId());
        attributes.put("groupId", getGroupId());
        attributes.put("companyId", getCompanyId());
        attributes.put("userId", getUserId());
        attributes.put("userName", getUserName());
        attributes.put("createDate", getCreateDate());
        attributes.put("modifiedDate", getModifiedDate());
        attributes.put("nombre", getNombre());
        attributes.put("descripcion", getDescripcion());
        attributes.put("precio", getPrecio());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        String uuid = (String) attributes.get("uuid");

        if (uuid != null) {
            setUuid(uuid);
        }

        Long productoId = (Long) attributes.get("productoId");

        if (productoId != null) {
            setProductoId(productoId);
        }

        Long groupId = (Long) attributes.get("groupId");

        if (groupId != null) {
            setGroupId(groupId);
        }

        Long companyId = (Long) attributes.get("companyId");

        if (companyId != null) {
            setCompanyId(companyId);
        }

        Long userId = (Long) attributes.get("userId");

        if (userId != null) {
            setUserId(userId);
        }

        String userName = (String) attributes.get("userName");

        if (userName != null) {
            setUserName(userName);
        }

        Date createDate = (Date) attributes.get("createDate");

        if (createDate != null) {
            setCreateDate(createDate);
        }

        Date modifiedDate = (Date) attributes.get("modifiedDate");

        if (modifiedDate != null) {
            setModifiedDate(modifiedDate);
        }

        String nombre = (String) attributes.get("nombre");

        if (nombre != null) {
            setNombre(nombre);
        }

        String descripcion = (String) attributes.get("descripcion");

        if (descripcion != null) {
            setDescripcion(descripcion);
        }

        Double precio = (Double) attributes.get("precio");

        if (precio != null) {
            setPrecio(precio);
        }
    }

    @JSON
    @Override
    public String getUuid() {
        if (_uuid == null) {
            return StringPool.BLANK;
        } else {
            return _uuid;
        }
    }

    @Override
    public void setUuid(String uuid) {
        if (_originalUuid == null) {
            _originalUuid = _uuid;
        }

        _uuid = uuid;
    }

    public String getOriginalUuid() {
        return GetterUtil.getString(_originalUuid);
    }

    @JSON
    @Override
    public long getProductoId() {
        return _productoId;
    }

    @Override
    public void setProductoId(long productoId) {
        _productoId = productoId;
    }

    @JSON
    @Override
    public long getGroupId() {
        return _groupId;
    }

    @Override
    public void setGroupId(long groupId) {
        _columnBitmask |= GROUPID_COLUMN_BITMASK;

        if (!_setOriginalGroupId) {
            _setOriginalGroupId = true;

            _originalGroupId = _groupId;
        }

        _groupId = groupId;
    }

    public long getOriginalGroupId() {
        return _originalGroupId;
    }

    @JSON
    @Override
    public long getCompanyId() {
        return _companyId;
    }

    @Override
    public void setCompanyId(long companyId) {
        _columnBitmask |= COMPANYID_COLUMN_BITMASK;

        if (!_setOriginalCompanyId) {
            _setOriginalCompanyId = true;

            _originalCompanyId = _companyId;
        }

        _companyId = companyId;
    }

    public long getOriginalCompanyId() {
        return _originalCompanyId;
    }

    @JSON
    @Override
    public long getUserId() {
        return _userId;
    }

    @Override
    public void setUserId(long userId) {
        _userId = userId;
    }

    @Override
    public String getUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
    }

    @Override
    public void setUserUuid(String userUuid) {
        _userUuid = userUuid;
    }

    @JSON
    @Override
    public String getUserName() {
        if (_userName == null) {
            return StringPool.BLANK;
        } else {
            return _userName;
        }
    }

    @Override
    public void setUserName(String userName) {
        _userName = userName;
    }

    @JSON
    @Override
    public Date getCreateDate() {
        return _createDate;
    }

    @Override
    public void setCreateDate(Date createDate) {
        _createDate = createDate;
    }

    @JSON
    @Override
    public Date getModifiedDate() {
        return _modifiedDate;
    }

    @Override
    public void setModifiedDate(Date modifiedDate) {
        _modifiedDate = modifiedDate;
    }

    @JSON
    @Override
    public String getNombre() {
        if (_nombre == null) {
            return StringPool.BLANK;
        } else {
            return _nombre;
        }
    }

    @Override
    public void setNombre(String nombre) {
        _columnBitmask = -1L;

        if (_originalNombre == null) {
            _originalNombre = _nombre;
        }

        _nombre = nombre;
    }

    public String getOriginalNombre() {
        return GetterUtil.getString(_originalNombre);
    }

    @JSON
    @Override
    public String getDescripcion() {
        if (_descripcion == null) {
            return StringPool.BLANK;
        } else {
            return _descripcion;
        }
    }

    @Override
    public void setDescripcion(String descripcion) {
        _descripcion = descripcion;
    }

    @JSON
    @Override
    public double getPrecio() {
        return _precio;
    }

    @Override
    public void setPrecio(double precio) {
        _columnBitmask |= PRECIO_COLUMN_BITMASK;

        if (!_setOriginalPrecio) {
            _setOriginalPrecio = true;

            _originalPrecio = _precio;
        }

        _precio = precio;
    }

    public double getOriginalPrecio() {
        return _originalPrecio;
    }

    @Override
    public StagedModelType getStagedModelType() {
        return new StagedModelType(PortalUtil.getClassNameId(
                Producto.class.getName()));
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
            Producto.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Producto toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Producto) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        ProductoImpl productoImpl = new ProductoImpl();

        productoImpl.setUuid(getUuid());
        productoImpl.setProductoId(getProductoId());
        productoImpl.setGroupId(getGroupId());
        productoImpl.setCompanyId(getCompanyId());
        productoImpl.setUserId(getUserId());
        productoImpl.setUserName(getUserName());
        productoImpl.setCreateDate(getCreateDate());
        productoImpl.setModifiedDate(getModifiedDate());
        productoImpl.setNombre(getNombre());
        productoImpl.setDescripcion(getDescripcion());
        productoImpl.setPrecio(getPrecio());

        productoImpl.resetOriginalValues();

        return productoImpl;
    }

    @Override
    public int compareTo(Producto producto) {
        int value = 0;

        value = getNombre().compareTo(producto.getNombre());

        if (value != 0) {
            return value;
        }

        return 0;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Producto)) {
            return false;
        }

        Producto producto = (Producto) obj;

        long primaryKey = producto.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        ProductoModelImpl productoModelImpl = this;

        productoModelImpl._originalUuid = productoModelImpl._uuid;

        productoModelImpl._originalGroupId = productoModelImpl._groupId;

        productoModelImpl._setOriginalGroupId = false;

        productoModelImpl._originalCompanyId = productoModelImpl._companyId;

        productoModelImpl._setOriginalCompanyId = false;

        productoModelImpl._originalNombre = productoModelImpl._nombre;

        productoModelImpl._originalPrecio = productoModelImpl._precio;

        productoModelImpl._setOriginalPrecio = false;

        productoModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<Producto> toCacheModel() {
        ProductoCacheModel productoCacheModel = new ProductoCacheModel();

        productoCacheModel.uuid = getUuid();

        String uuid = productoCacheModel.uuid;

        if ((uuid != null) && (uuid.length() == 0)) {
            productoCacheModel.uuid = null;
        }

        productoCacheModel.productoId = getProductoId();

        productoCacheModel.groupId = getGroupId();

        productoCacheModel.companyId = getCompanyId();

        productoCacheModel.userId = getUserId();

        productoCacheModel.userName = getUserName();

        String userName = productoCacheModel.userName;

        if ((userName != null) && (userName.length() == 0)) {
            productoCacheModel.userName = null;
        }

        Date createDate = getCreateDate();

        if (createDate != null) {
            productoCacheModel.createDate = createDate.getTime();
        } else {
            productoCacheModel.createDate = Long.MIN_VALUE;
        }

        Date modifiedDate = getModifiedDate();

        if (modifiedDate != null) {
            productoCacheModel.modifiedDate = modifiedDate.getTime();
        } else {
            productoCacheModel.modifiedDate = Long.MIN_VALUE;
        }

        productoCacheModel.nombre = getNombre();

        String nombre = productoCacheModel.nombre;

        if ((nombre != null) && (nombre.length() == 0)) {
            productoCacheModel.nombre = null;
        }

        productoCacheModel.descripcion = getDescripcion();

        String descripcion = productoCacheModel.descripcion;

        if ((descripcion != null) && (descripcion.length() == 0)) {
            productoCacheModel.descripcion = null;
        }

        productoCacheModel.precio = getPrecio();

        return productoCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(23);

        sb.append("{uuid=");
        sb.append(getUuid());
        sb.append(", productoId=");
        sb.append(getProductoId());
        sb.append(", groupId=");
        sb.append(getGroupId());
        sb.append(", companyId=");
        sb.append(getCompanyId());
        sb.append(", userId=");
        sb.append(getUserId());
        sb.append(", userName=");
        sb.append(getUserName());
        sb.append(", createDate=");
        sb.append(getCreateDate());
        sb.append(", modifiedDate=");
        sb.append(getModifiedDate());
        sb.append(", nombre=");
        sb.append(getNombre());
        sb.append(", descripcion=");
        sb.append(getDescripcion());
        sb.append(", precio=");
        sb.append(getPrecio());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(37);

        sb.append("<model><model-name>");
        sb.append("com.example.plugins.model.Producto");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>uuid</column-name><column-value><![CDATA[");
        sb.append(getUuid());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>productoId</column-name><column-value><![CDATA[");
        sb.append(getProductoId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>groupId</column-name><column-value><![CDATA[");
        sb.append(getGroupId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>companyId</column-name><column-value><![CDATA[");
        sb.append(getCompanyId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userId</column-name><column-value><![CDATA[");
        sb.append(getUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userName</column-name><column-value><![CDATA[");
        sb.append(getUserName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>createDate</column-name><column-value><![CDATA[");
        sb.append(getCreateDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
        sb.append(getModifiedDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>nombre</column-name><column-value><![CDATA[");
        sb.append(getNombre());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>descripcion</column-name><column-value><![CDATA[");
        sb.append(getDescripcion());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>precio</column-name><column-value><![CDATA[");
        sb.append(getPrecio());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
