package com.example.plugins.model.impl;

import com.example.plugins.model.Puja;
import com.example.plugins.service.PujaLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Puja service. Represents a row in the &quot;Subastas_Puja&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PujaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PujaImpl
 * @see com.example.plugins.model.Puja
 * @generated
 */
public abstract class PujaBaseImpl extends PujaModelImpl implements Puja {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a puja model instance should use the {@link Puja} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            PujaLocalServiceUtil.addPuja(this);
        } else {
            PujaLocalServiceUtil.updatePuja(this);
        }
    }
}
