package com.example.plugins.model.impl;

import com.example.plugins.model.Puja;
import com.example.plugins.model.PujaModel;
import com.example.plugins.model.PujaSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Puja service. Represents a row in the &quot;Subastas_Puja&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.example.plugins.model.PujaModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PujaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PujaImpl
 * @see com.example.plugins.model.Puja
 * @see com.example.plugins.model.PujaModel
 * @generated
 */
@JSON(strict = true)
public class PujaModelImpl extends BaseModelImpl<Puja> implements PujaModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a puja model instance should use the {@link com.example.plugins.model.Puja} interface instead.
     */
    public static final String TABLE_NAME = "Subastas_Puja";
    public static final Object[][] TABLE_COLUMNS = {
            { "uuid_", Types.VARCHAR },
            { "pujaId", Types.BIGINT },
            { "groupId", Types.BIGINT },
            { "companyId", Types.BIGINT },
            { "userId", Types.BIGINT },
            { "userName", Types.VARCHAR },
            { "createDate", Types.TIMESTAMP },
            { "modifiedDate", Types.TIMESTAMP },
            { "valor", Types.DOUBLE },
            { "subastaId", Types.BIGINT }
        };
    public static final String TABLE_SQL_CREATE = "create table Subastas_Puja (uuid_ VARCHAR(75) null,pujaId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,valor DOUBLE,subastaId LONG)";
    public static final String TABLE_SQL_DROP = "drop table Subastas_Puja";
    public static final String ORDER_BY_JPQL = " ORDER BY puja.valor ASC";
    public static final String ORDER_BY_SQL = " ORDER BY Subastas_Puja.valor ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.example.plugins.model.Puja"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.example.plugins.model.Puja"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.com.example.plugins.model.Puja"),
            true);
    public static long COMPANYID_COLUMN_BITMASK = 1L;
    public static long GROUPID_COLUMN_BITMASK = 2L;
    public static long SUBASTAID_COLUMN_BITMASK = 4L;
    public static long UUID_COLUMN_BITMASK = 8L;
    public static long VALOR_COLUMN_BITMASK = 16L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.example.plugins.model.Puja"));
    private static ClassLoader _classLoader = Puja.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] { Puja.class };
    private String _uuid;
    private String _originalUuid;
    private long _pujaId;
    private long _groupId;
    private long _originalGroupId;
    private boolean _setOriginalGroupId;
    private long _companyId;
    private long _originalCompanyId;
    private boolean _setOriginalCompanyId;
    private long _userId;
    private String _userUuid;
    private String _userName;
    private Date _createDate;
    private Date _modifiedDate;
    private double _valor;
    private long _subastaId;
    private long _originalSubastaId;
    private boolean _setOriginalSubastaId;
    private long _columnBitmask;
    private Puja _escapedModel;

    public PujaModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static Puja toModel(PujaSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        Puja model = new PujaImpl();

        model.setUuid(soapModel.getUuid());
        model.setPujaId(soapModel.getPujaId());
        model.setGroupId(soapModel.getGroupId());
        model.setCompanyId(soapModel.getCompanyId());
        model.setUserId(soapModel.getUserId());
        model.setUserName(soapModel.getUserName());
        model.setCreateDate(soapModel.getCreateDate());
        model.setModifiedDate(soapModel.getModifiedDate());
        model.setValor(soapModel.getValor());
        model.setSubastaId(soapModel.getSubastaId());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<Puja> toModels(PujaSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<Puja> models = new ArrayList<Puja>(soapModels.length);

        for (PujaSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _pujaId;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setPujaId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _pujaId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Puja.class;
    }

    @Override
    public String getModelClassName() {
        return Puja.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("uuid", getUuid());
        attributes.put("pujaId", getPujaId());
        attributes.put("groupId", getGroupId());
        attributes.put("companyId", getCompanyId());
        attributes.put("userId", getUserId());
        attributes.put("userName", getUserName());
        attributes.put("createDate", getCreateDate());
        attributes.put("modifiedDate", getModifiedDate());
        attributes.put("valor", getValor());
        attributes.put("subastaId", getSubastaId());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        String uuid = (String) attributes.get("uuid");

        if (uuid != null) {
            setUuid(uuid);
        }

        Long pujaId = (Long) attributes.get("pujaId");

        if (pujaId != null) {
            setPujaId(pujaId);
        }

        Long groupId = (Long) attributes.get("groupId");

        if (groupId != null) {
            setGroupId(groupId);
        }

        Long companyId = (Long) attributes.get("companyId");

        if (companyId != null) {
            setCompanyId(companyId);
        }

        Long userId = (Long) attributes.get("userId");

        if (userId != null) {
            setUserId(userId);
        }

        String userName = (String) attributes.get("userName");

        if (userName != null) {
            setUserName(userName);
        }

        Date createDate = (Date) attributes.get("createDate");

        if (createDate != null) {
            setCreateDate(createDate);
        }

        Date modifiedDate = (Date) attributes.get("modifiedDate");

        if (modifiedDate != null) {
            setModifiedDate(modifiedDate);
        }

        Double valor = (Double) attributes.get("valor");

        if (valor != null) {
            setValor(valor);
        }

        Long subastaId = (Long) attributes.get("subastaId");

        if (subastaId != null) {
            setSubastaId(subastaId);
        }
    }

    @JSON
    @Override
    public String getUuid() {
        if (_uuid == null) {
            return StringPool.BLANK;
        } else {
            return _uuid;
        }
    }

    @Override
    public void setUuid(String uuid) {
        if (_originalUuid == null) {
            _originalUuid = _uuid;
        }

        _uuid = uuid;
    }

    public String getOriginalUuid() {
        return GetterUtil.getString(_originalUuid);
    }

    @JSON
    @Override
    public long getPujaId() {
        return _pujaId;
    }

    @Override
    public void setPujaId(long pujaId) {
        _pujaId = pujaId;
    }

    @JSON
    @Override
    public long getGroupId() {
        return _groupId;
    }

    @Override
    public void setGroupId(long groupId) {
        _columnBitmask |= GROUPID_COLUMN_BITMASK;

        if (!_setOriginalGroupId) {
            _setOriginalGroupId = true;

            _originalGroupId = _groupId;
        }

        _groupId = groupId;
    }

    public long getOriginalGroupId() {
        return _originalGroupId;
    }

    @JSON
    @Override
    public long getCompanyId() {
        return _companyId;
    }

    @Override
    public void setCompanyId(long companyId) {
        _columnBitmask |= COMPANYID_COLUMN_BITMASK;

        if (!_setOriginalCompanyId) {
            _setOriginalCompanyId = true;

            _originalCompanyId = _companyId;
        }

        _companyId = companyId;
    }

    public long getOriginalCompanyId() {
        return _originalCompanyId;
    }

    @JSON
    @Override
    public long getUserId() {
        return _userId;
    }

    @Override
    public void setUserId(long userId) {
        _userId = userId;
    }

    @Override
    public String getUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
    }

    @Override
    public void setUserUuid(String userUuid) {
        _userUuid = userUuid;
    }

    @JSON
    @Override
    public String getUserName() {
        if (_userName == null) {
            return StringPool.BLANK;
        } else {
            return _userName;
        }
    }

    @Override
    public void setUserName(String userName) {
        _userName = userName;
    }

    @JSON
    @Override
    public Date getCreateDate() {
        return _createDate;
    }

    @Override
    public void setCreateDate(Date createDate) {
        _createDate = createDate;
    }

    @JSON
    @Override
    public Date getModifiedDate() {
        return _modifiedDate;
    }

    @Override
    public void setModifiedDate(Date modifiedDate) {
        _modifiedDate = modifiedDate;
    }

    @JSON
    @Override
    public double getValor() {
        return _valor;
    }

    @Override
    public void setValor(double valor) {
        _columnBitmask = -1L;

        _valor = valor;
    }

    @JSON
    @Override
    public long getSubastaId() {
        return _subastaId;
    }

    @Override
    public void setSubastaId(long subastaId) {
        _columnBitmask |= SUBASTAID_COLUMN_BITMASK;

        if (!_setOriginalSubastaId) {
            _setOriginalSubastaId = true;

            _originalSubastaId = _subastaId;
        }

        _subastaId = subastaId;
    }

    public long getOriginalSubastaId() {
        return _originalSubastaId;
    }

    @Override
    public StagedModelType getStagedModelType() {
        return new StagedModelType(PortalUtil.getClassNameId(
                Puja.class.getName()));
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
            Puja.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Puja toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Puja) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        PujaImpl pujaImpl = new PujaImpl();

        pujaImpl.setUuid(getUuid());
        pujaImpl.setPujaId(getPujaId());
        pujaImpl.setGroupId(getGroupId());
        pujaImpl.setCompanyId(getCompanyId());
        pujaImpl.setUserId(getUserId());
        pujaImpl.setUserName(getUserName());
        pujaImpl.setCreateDate(getCreateDate());
        pujaImpl.setModifiedDate(getModifiedDate());
        pujaImpl.setValor(getValor());
        pujaImpl.setSubastaId(getSubastaId());

        pujaImpl.resetOriginalValues();

        return pujaImpl;
    }

    @Override
    public int compareTo(Puja puja) {
        int value = 0;

        if (getValor() < puja.getValor()) {
            value = -1;
        } else if (getValor() > puja.getValor()) {
            value = 1;
        } else {
            value = 0;
        }

        if (value != 0) {
            return value;
        }

        return 0;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Puja)) {
            return false;
        }

        Puja puja = (Puja) obj;

        long primaryKey = puja.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        PujaModelImpl pujaModelImpl = this;

        pujaModelImpl._originalUuid = pujaModelImpl._uuid;

        pujaModelImpl._originalGroupId = pujaModelImpl._groupId;

        pujaModelImpl._setOriginalGroupId = false;

        pujaModelImpl._originalCompanyId = pujaModelImpl._companyId;

        pujaModelImpl._setOriginalCompanyId = false;

        pujaModelImpl._originalSubastaId = pujaModelImpl._subastaId;

        pujaModelImpl._setOriginalSubastaId = false;

        pujaModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<Puja> toCacheModel() {
        PujaCacheModel pujaCacheModel = new PujaCacheModel();

        pujaCacheModel.uuid = getUuid();

        String uuid = pujaCacheModel.uuid;

        if ((uuid != null) && (uuid.length() == 0)) {
            pujaCacheModel.uuid = null;
        }

        pujaCacheModel.pujaId = getPujaId();

        pujaCacheModel.groupId = getGroupId();

        pujaCacheModel.companyId = getCompanyId();

        pujaCacheModel.userId = getUserId();

        pujaCacheModel.userName = getUserName();

        String userName = pujaCacheModel.userName;

        if ((userName != null) && (userName.length() == 0)) {
            pujaCacheModel.userName = null;
        }

        Date createDate = getCreateDate();

        if (createDate != null) {
            pujaCacheModel.createDate = createDate.getTime();
        } else {
            pujaCacheModel.createDate = Long.MIN_VALUE;
        }

        Date modifiedDate = getModifiedDate();

        if (modifiedDate != null) {
            pujaCacheModel.modifiedDate = modifiedDate.getTime();
        } else {
            pujaCacheModel.modifiedDate = Long.MIN_VALUE;
        }

        pujaCacheModel.valor = getValor();

        pujaCacheModel.subastaId = getSubastaId();

        return pujaCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(21);

        sb.append("{uuid=");
        sb.append(getUuid());
        sb.append(", pujaId=");
        sb.append(getPujaId());
        sb.append(", groupId=");
        sb.append(getGroupId());
        sb.append(", companyId=");
        sb.append(getCompanyId());
        sb.append(", userId=");
        sb.append(getUserId());
        sb.append(", userName=");
        sb.append(getUserName());
        sb.append(", createDate=");
        sb.append(getCreateDate());
        sb.append(", modifiedDate=");
        sb.append(getModifiedDate());
        sb.append(", valor=");
        sb.append(getValor());
        sb.append(", subastaId=");
        sb.append(getSubastaId());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(34);

        sb.append("<model><model-name>");
        sb.append("com.example.plugins.model.Puja");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>uuid</column-name><column-value><![CDATA[");
        sb.append(getUuid());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>pujaId</column-name><column-value><![CDATA[");
        sb.append(getPujaId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>groupId</column-name><column-value><![CDATA[");
        sb.append(getGroupId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>companyId</column-name><column-value><![CDATA[");
        sb.append(getCompanyId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userId</column-name><column-value><![CDATA[");
        sb.append(getUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userName</column-name><column-value><![CDATA[");
        sb.append(getUserName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>createDate</column-name><column-value><![CDATA[");
        sb.append(getCreateDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
        sb.append(getModifiedDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>valor</column-name><column-value><![CDATA[");
        sb.append(getValor());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>subastaId</column-name><column-value><![CDATA[");
        sb.append(getSubastaId());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
