package com.example.plugins.model.impl;

import com.example.plugins.model.Subasta;
import com.example.plugins.model.SubastaModel;
import com.example.plugins.model.SubastaSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Subasta service. Represents a row in the &quot;Subastas_Subasta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.example.plugins.model.SubastaModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SubastaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SubastaImpl
 * @see com.example.plugins.model.Subasta
 * @see com.example.plugins.model.SubastaModel
 * @generated
 */
@JSON(strict = true)
public class SubastaModelImpl extends BaseModelImpl<Subasta>
    implements SubastaModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a subasta model instance should use the {@link com.example.plugins.model.Subasta} interface instead.
     */
    public static final String TABLE_NAME = "Subastas_Subasta";
    public static final Object[][] TABLE_COLUMNS = {
            { "uuid_", Types.VARCHAR },
            { "subastaId", Types.BIGINT },
            { "groupId", Types.BIGINT },
            { "companyId", Types.BIGINT },
            { "userId", Types.BIGINT },
            { "userName", Types.VARCHAR },
            { "createDate", Types.TIMESTAMP },
            { "modifiedDate", Types.TIMESTAMP },
            { "precioMinimo", Types.DOUBLE },
            { "fechaInicio", Types.TIMESTAMP },
            { "fechaFin", Types.TIMESTAMP },
            { "productoId", Types.BIGINT }
        };
    public static final String TABLE_SQL_CREATE = "create table Subastas_Subasta (uuid_ VARCHAR(75) null,subastaId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,precioMinimo DOUBLE,fechaInicio DATE null,fechaFin DATE null,productoId LONG)";
    public static final String TABLE_SQL_DROP = "drop table Subastas_Subasta";
    public static final String ORDER_BY_JPQL = " ORDER BY subasta.precioMinimo ASC";
    public static final String ORDER_BY_SQL = " ORDER BY Subastas_Subasta.precioMinimo ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.example.plugins.model.Subasta"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.example.plugins.model.Subasta"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.com.example.plugins.model.Subasta"),
            true);
    public static long COMPANYID_COLUMN_BITMASK = 1L;
    public static long FECHAFIN_COLUMN_BITMASK = 2L;
    public static long FECHAINICIO_COLUMN_BITMASK = 4L;
    public static long GROUPID_COLUMN_BITMASK = 8L;
    public static long UUID_COLUMN_BITMASK = 16L;
    public static long PRECIOMINIMO_COLUMN_BITMASK = 32L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.example.plugins.model.Subasta"));
    private static ClassLoader _classLoader = Subasta.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            Subasta.class
        };
    private String _uuid;
    private String _originalUuid;
    private long _subastaId;
    private long _groupId;
    private long _originalGroupId;
    private boolean _setOriginalGroupId;
    private long _companyId;
    private long _originalCompanyId;
    private boolean _setOriginalCompanyId;
    private long _userId;
    private String _userUuid;
    private String _userName;
    private Date _createDate;
    private Date _modifiedDate;
    private double _precioMinimo;
    private Date _fechaInicio;
    private Date _originalFechaInicio;
    private Date _fechaFin;
    private Date _originalFechaFin;
    private long _productoId;
    private long _columnBitmask;
    private Subasta _escapedModel;

    public SubastaModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static Subasta toModel(SubastaSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        Subasta model = new SubastaImpl();

        model.setUuid(soapModel.getUuid());
        model.setSubastaId(soapModel.getSubastaId());
        model.setGroupId(soapModel.getGroupId());
        model.setCompanyId(soapModel.getCompanyId());
        model.setUserId(soapModel.getUserId());
        model.setUserName(soapModel.getUserName());
        model.setCreateDate(soapModel.getCreateDate());
        model.setModifiedDate(soapModel.getModifiedDate());
        model.setPrecioMinimo(soapModel.getPrecioMinimo());
        model.setFechaInicio(soapModel.getFechaInicio());
        model.setFechaFin(soapModel.getFechaFin());
        model.setProductoId(soapModel.getProductoId());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<Subasta> toModels(SubastaSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<Subasta> models = new ArrayList<Subasta>(soapModels.length);

        for (SubastaSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _subastaId;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setSubastaId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _subastaId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Subasta.class;
    }

    @Override
    public String getModelClassName() {
        return Subasta.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("uuid", getUuid());
        attributes.put("subastaId", getSubastaId());
        attributes.put("groupId", getGroupId());
        attributes.put("companyId", getCompanyId());
        attributes.put("userId", getUserId());
        attributes.put("userName", getUserName());
        attributes.put("createDate", getCreateDate());
        attributes.put("modifiedDate", getModifiedDate());
        attributes.put("precioMinimo", getPrecioMinimo());
        attributes.put("fechaInicio", getFechaInicio());
        attributes.put("fechaFin", getFechaFin());
        attributes.put("productoId", getProductoId());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        String uuid = (String) attributes.get("uuid");

        if (uuid != null) {
            setUuid(uuid);
        }

        Long subastaId = (Long) attributes.get("subastaId");

        if (subastaId != null) {
            setSubastaId(subastaId);
        }

        Long groupId = (Long) attributes.get("groupId");

        if (groupId != null) {
            setGroupId(groupId);
        }

        Long companyId = (Long) attributes.get("companyId");

        if (companyId != null) {
            setCompanyId(companyId);
        }

        Long userId = (Long) attributes.get("userId");

        if (userId != null) {
            setUserId(userId);
        }

        String userName = (String) attributes.get("userName");

        if (userName != null) {
            setUserName(userName);
        }

        Date createDate = (Date) attributes.get("createDate");

        if (createDate != null) {
            setCreateDate(createDate);
        }

        Date modifiedDate = (Date) attributes.get("modifiedDate");

        if (modifiedDate != null) {
            setModifiedDate(modifiedDate);
        }

        Double precioMinimo = (Double) attributes.get("precioMinimo");

        if (precioMinimo != null) {
            setPrecioMinimo(precioMinimo);
        }

        Date fechaInicio = (Date) attributes.get("fechaInicio");

        if (fechaInicio != null) {
            setFechaInicio(fechaInicio);
        }

        Date fechaFin = (Date) attributes.get("fechaFin");

        if (fechaFin != null) {
            setFechaFin(fechaFin);
        }

        Long productoId = (Long) attributes.get("productoId");

        if (productoId != null) {
            setProductoId(productoId);
        }
    }

    @JSON
    @Override
    public String getUuid() {
        if (_uuid == null) {
            return StringPool.BLANK;
        } else {
            return _uuid;
        }
    }

    @Override
    public void setUuid(String uuid) {
        if (_originalUuid == null) {
            _originalUuid = _uuid;
        }

        _uuid = uuid;
    }

    public String getOriginalUuid() {
        return GetterUtil.getString(_originalUuid);
    }

    @JSON
    @Override
    public long getSubastaId() {
        return _subastaId;
    }

    @Override
    public void setSubastaId(long subastaId) {
        _subastaId = subastaId;
    }

    @JSON
    @Override
    public long getGroupId() {
        return _groupId;
    }

    @Override
    public void setGroupId(long groupId) {
        _columnBitmask |= GROUPID_COLUMN_BITMASK;

        if (!_setOriginalGroupId) {
            _setOriginalGroupId = true;

            _originalGroupId = _groupId;
        }

        _groupId = groupId;
    }

    public long getOriginalGroupId() {
        return _originalGroupId;
    }

    @JSON
    @Override
    public long getCompanyId() {
        return _companyId;
    }

    @Override
    public void setCompanyId(long companyId) {
        _columnBitmask |= COMPANYID_COLUMN_BITMASK;

        if (!_setOriginalCompanyId) {
            _setOriginalCompanyId = true;

            _originalCompanyId = _companyId;
        }

        _companyId = companyId;
    }

    public long getOriginalCompanyId() {
        return _originalCompanyId;
    }

    @JSON
    @Override
    public long getUserId() {
        return _userId;
    }

    @Override
    public void setUserId(long userId) {
        _userId = userId;
    }

    @Override
    public String getUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
    }

    @Override
    public void setUserUuid(String userUuid) {
        _userUuid = userUuid;
    }

    @JSON
    @Override
    public String getUserName() {
        if (_userName == null) {
            return StringPool.BLANK;
        } else {
            return _userName;
        }
    }

    @Override
    public void setUserName(String userName) {
        _userName = userName;
    }

    @JSON
    @Override
    public Date getCreateDate() {
        return _createDate;
    }

    @Override
    public void setCreateDate(Date createDate) {
        _createDate = createDate;
    }

    @JSON
    @Override
    public Date getModifiedDate() {
        return _modifiedDate;
    }

    @Override
    public void setModifiedDate(Date modifiedDate) {
        _modifiedDate = modifiedDate;
    }

    @JSON
    @Override
    public double getPrecioMinimo() {
        return _precioMinimo;
    }

    @Override
    public void setPrecioMinimo(double precioMinimo) {
        _columnBitmask = -1L;

        _precioMinimo = precioMinimo;
    }

    @JSON
    @Override
    public Date getFechaInicio() {
        return _fechaInicio;
    }

    @Override
    public void setFechaInicio(Date fechaInicio) {
        _columnBitmask |= FECHAINICIO_COLUMN_BITMASK;

        if (_originalFechaInicio == null) {
            _originalFechaInicio = _fechaInicio;
        }

        _fechaInicio = fechaInicio;
    }

    public Date getOriginalFechaInicio() {
        return _originalFechaInicio;
    }

    @JSON
    @Override
    public Date getFechaFin() {
        return _fechaFin;
    }

    @Override
    public void setFechaFin(Date fechaFin) {
        _columnBitmask |= FECHAFIN_COLUMN_BITMASK;

        if (_originalFechaFin == null) {
            _originalFechaFin = _fechaFin;
        }

        _fechaFin = fechaFin;
    }

    public Date getOriginalFechaFin() {
        return _originalFechaFin;
    }

    @JSON
    @Override
    public long getProductoId() {
        return _productoId;
    }

    @Override
    public void setProductoId(long productoId) {
        _productoId = productoId;
    }

    @Override
    public StagedModelType getStagedModelType() {
        return new StagedModelType(PortalUtil.getClassNameId(
                Subasta.class.getName()));
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
            Subasta.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Subasta toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Subasta) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        SubastaImpl subastaImpl = new SubastaImpl();

        subastaImpl.setUuid(getUuid());
        subastaImpl.setSubastaId(getSubastaId());
        subastaImpl.setGroupId(getGroupId());
        subastaImpl.setCompanyId(getCompanyId());
        subastaImpl.setUserId(getUserId());
        subastaImpl.setUserName(getUserName());
        subastaImpl.setCreateDate(getCreateDate());
        subastaImpl.setModifiedDate(getModifiedDate());
        subastaImpl.setPrecioMinimo(getPrecioMinimo());
        subastaImpl.setFechaInicio(getFechaInicio());
        subastaImpl.setFechaFin(getFechaFin());
        subastaImpl.setProductoId(getProductoId());

        subastaImpl.resetOriginalValues();

        return subastaImpl;
    }

    @Override
    public int compareTo(Subasta subasta) {
        int value = 0;

        if (getPrecioMinimo() < subasta.getPrecioMinimo()) {
            value = -1;
        } else if (getPrecioMinimo() > subasta.getPrecioMinimo()) {
            value = 1;
        } else {
            value = 0;
        }

        if (value != 0) {
            return value;
        }

        return 0;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Subasta)) {
            return false;
        }

        Subasta subasta = (Subasta) obj;

        long primaryKey = subasta.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        SubastaModelImpl subastaModelImpl = this;

        subastaModelImpl._originalUuid = subastaModelImpl._uuid;

        subastaModelImpl._originalGroupId = subastaModelImpl._groupId;

        subastaModelImpl._setOriginalGroupId = false;

        subastaModelImpl._originalCompanyId = subastaModelImpl._companyId;

        subastaModelImpl._setOriginalCompanyId = false;

        subastaModelImpl._originalFechaInicio = subastaModelImpl._fechaInicio;

        subastaModelImpl._originalFechaFin = subastaModelImpl._fechaFin;

        subastaModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<Subasta> toCacheModel() {
        SubastaCacheModel subastaCacheModel = new SubastaCacheModel();

        subastaCacheModel.uuid = getUuid();

        String uuid = subastaCacheModel.uuid;

        if ((uuid != null) && (uuid.length() == 0)) {
            subastaCacheModel.uuid = null;
        }

        subastaCacheModel.subastaId = getSubastaId();

        subastaCacheModel.groupId = getGroupId();

        subastaCacheModel.companyId = getCompanyId();

        subastaCacheModel.userId = getUserId();

        subastaCacheModel.userName = getUserName();

        String userName = subastaCacheModel.userName;

        if ((userName != null) && (userName.length() == 0)) {
            subastaCacheModel.userName = null;
        }

        Date createDate = getCreateDate();

        if (createDate != null) {
            subastaCacheModel.createDate = createDate.getTime();
        } else {
            subastaCacheModel.createDate = Long.MIN_VALUE;
        }

        Date modifiedDate = getModifiedDate();

        if (modifiedDate != null) {
            subastaCacheModel.modifiedDate = modifiedDate.getTime();
        } else {
            subastaCacheModel.modifiedDate = Long.MIN_VALUE;
        }

        subastaCacheModel.precioMinimo = getPrecioMinimo();

        Date fechaInicio = getFechaInicio();

        if (fechaInicio != null) {
            subastaCacheModel.fechaInicio = fechaInicio.getTime();
        } else {
            subastaCacheModel.fechaInicio = Long.MIN_VALUE;
        }

        Date fechaFin = getFechaFin();

        if (fechaFin != null) {
            subastaCacheModel.fechaFin = fechaFin.getTime();
        } else {
            subastaCacheModel.fechaFin = Long.MIN_VALUE;
        }

        subastaCacheModel.productoId = getProductoId();

        return subastaCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(25);

        sb.append("{uuid=");
        sb.append(getUuid());
        sb.append(", subastaId=");
        sb.append(getSubastaId());
        sb.append(", groupId=");
        sb.append(getGroupId());
        sb.append(", companyId=");
        sb.append(getCompanyId());
        sb.append(", userId=");
        sb.append(getUserId());
        sb.append(", userName=");
        sb.append(getUserName());
        sb.append(", createDate=");
        sb.append(getCreateDate());
        sb.append(", modifiedDate=");
        sb.append(getModifiedDate());
        sb.append(", precioMinimo=");
        sb.append(getPrecioMinimo());
        sb.append(", fechaInicio=");
        sb.append(getFechaInicio());
        sb.append(", fechaFin=");
        sb.append(getFechaFin());
        sb.append(", productoId=");
        sb.append(getProductoId());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(40);

        sb.append("<model><model-name>");
        sb.append("com.example.plugins.model.Subasta");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>uuid</column-name><column-value><![CDATA[");
        sb.append(getUuid());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>subastaId</column-name><column-value><![CDATA[");
        sb.append(getSubastaId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>groupId</column-name><column-value><![CDATA[");
        sb.append(getGroupId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>companyId</column-name><column-value><![CDATA[");
        sb.append(getCompanyId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userId</column-name><column-value><![CDATA[");
        sb.append(getUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userName</column-name><column-value><![CDATA[");
        sb.append(getUserName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>createDate</column-name><column-value><![CDATA[");
        sb.append(getCreateDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
        sb.append(getModifiedDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>precioMinimo</column-name><column-value><![CDATA[");
        sb.append(getPrecioMinimo());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>fechaInicio</column-name><column-value><![CDATA[");
        sb.append(getFechaInicio());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>fechaFin</column-name><column-value><![CDATA[");
        sb.append(getFechaFin());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>productoId</column-name><column-value><![CDATA[");
        sb.append(getProductoId());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
